### ISSUE TITLE
Get settings from config file

### ISSUE THREAD

**Issue by Larke12** [Larke12/twicciand#3]
Have the background daemon read/write settings to a config file, such as login information and user options.

**Comment by octotep** [comment]
Settings are now read and written from a config file in the same directory. I think that's good enough for the minimal working system, but for the 50% working system, we should let the program check in a few specified locations, like `$HOME/.config/twicciand` for the config file.

If we ever want to install this program on a users computer, keeping the config file in the same directory as the binary isn't going to work out in terms of permissions

**Comment by octotep** [comment]
fixed in a5089e9324643538f656ba0ad87aabd9b1f2d95f
